USE [PhoneBook]
GO

DROP TABLE IF EXISTS [dbo].[PHONE_NUMBERS]
GO

DROP TABLE IF EXISTS [dbo].[PERSONS]
GO

DROP TABLE IF EXISTS [dbo].[CITIES]
GO

DROP TABLE IF EXISTS [dbo].[PHONE_TYPES]
GO

CREATE TABLE [dbo].[CITIES]
(
	[ID] [INT] IDENTITY NOT NULL,
	[UPDATE_COUNTER] [INT] NOT NULL,
	[NAME] [NVARCHAR](64) NOT NULL,
	[REGION] [NVARCHAR](64) NOT NULL
)
GO

ALTER TABLE [dbo].[CITIES]
ADD CONSTRAINT PK_CITIES_ID PRIMARY KEY (ID)

ALTER TABLE [dbo].[CITIES]
ADD CONSTRAINT UX_CITIES_NAME_REGION UNIQUE ([NAME], [REGION])

GO
CREATE TABLE [dbo].[PHONE_TYPES]
(
	[ID] [INT] IDENTITY NOT NULL,
	[UPDATE_COUNTER] [INT] NOT NULL,
	[TYPE] [NCHAR](8) NOT NULL
)
GO

ALTER TABLE [dbo].[PHONE_TYPES]
ADD CONSTRAINT PK_PHONE_TYPES_ID PRIMARY KEY ([ID])

IF NOT EXISTS (SELECT NAME FROM sys.indexes WHERE NAME = 'UX_PHONE_TYPES_TYPE')
	CREATE UNIQUE INDEX UX_PHONE_TYPES_TYPE ON [PHONE_TYPES]([TYPE])

CREATE TABLE [dbo].[PERSONS]
(
	[ID] [INT] IDENTITY NOT NULL,
	[UPDATE_COUNTER] [INT] NOT NULL,
	[FIRST_NAME] [NVARCHAR](32) NOT NULL,
	[SECOND_NAME] [NVARCHAR](32) NOT NULL,
	[LAST_NAME] [NVARCHAR](32) NOT NULL,
	[IDENTIFICATION_NUMBER] [NVARCHAR](16) NOT NULL,
	[CITY_ID] [INT] NOT NULL,
	[ADDRESS] [NVARCHAR](64) NOT NULL
)
GO

ALTER TABLE [dbo].[PERSONS]
ADD CONSTRAINT PK_PERSONS_ID PRIMARY KEY ([ID])

ALTER TABLE [dbo].[PERSONS]
ADD CONSTRAINT FK_PERSONS_CITY_ID FOREIGN KEY (CITY_ID) REFERENCES [CITIES]([ID])

IF NOT EXISTS ( SELECT NAME FROM sys.indexes WHERE NAME = 'IX_PERSONS_CITY_ID' )
	CREATE INDEX IX_PERSONS_CITY_ID ON [PERSONS]([CITY_ID])

IF NOT EXISTS ( SELECT NAME FROM sys.indexes WHERE NAME = 'UX_PERSONS_IDENTIFICATION_NUMBER' )
	CREATE UNIQUE INDEX UX_PERSONS_IDENTIFICATION_NUMBER ON [PERSONS]([IDENTIFICATION_NUMBER])

GO

CREATE TABLE [dbo].[PHONE_NUMBERS]
(
	[ID] [INT] NOT NULL IDENTITY,
	[UPDATE_COUNTER] [INT] NOT NULL,
	[PERSON_ID] [INT] NOT NULL,
	[PHONE_TYPES_ID] [INT] NOT NULL,
	[NUMBER] [NVARCHAR](16) NOT NULL
)
GO

ALTER TABLE [dbo].[PHONE_NUMBERS]
ADD CONSTRAINT PK_PHONE_NUMBERS_ID PRIMARY KEY (ID)

ALTER TABLE [dbo].[PHONE_NUMBERS]
ADD CONSTRAINT FK_PHONE_NUMBERS_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES [PERSONS]([ID])

IF NOT EXISTS (SELECT name FROM sys.indexes WHERE name = 'IX_PHONE_NUMBERS_PERSON_ID')
	CREATE INDEX IX_PHONE_NUMBERS_PERSON_ID ON [PHONE_NUMBERS]([PERSON_ID])

ALTER TABLE [dbo].[PHONE_NUMBERS]
ADD CONSTRAINT FK_PHONE_NUMBERS_PHONE_TYPES_ID FOREIGN KEY (PHONE_TYPES_ID) REFERENCES [PHONE_TYPES]([ID])

IF NOT EXISTS (SELECT NAME FROM sys.indexes WHERE NAME = 'IX_PHONE_NUMBERS_PHONE_TYPES_ID')
	CREATE INDEX IX_PHONE_NUMBERS_PHONE_TYPES_ID ON [PHONE_NUMBERS]([PHONE_TYPES_ID])

IF NOT EXISTS (SELECT NAME FROM sys.indexes WHERE NAME = 'UX_PHONE_NUMBERS_NUMBER')
	CREATE UNIQUE INDEX UX_PHONE_NUMBERS_NUMBER ON [PHONE_NUMBERS]([NUMBER])
GO